ALTER TABLE products ALTER COLUMN description VARCHAR(1000);

INSERT INTO products (name, description, price, is_available) VALUES 
('Smart TV', 'Veja o mundo como nunca viu', 1199.99, TRUE),
('Smartphone', 'O mundo em suas mãos', 1999.90, TRUE),
('Laptop', 'Incrivelmente rápido, pequeno e elegante', 4695.00, FALSE),
('Freezer', 'Estou congelando 🥶', 749.50, TRUE),
('Chuveiro Elétrico', 'Banho quentinho sem levar choque', 149.90, TRUE),
('Smartwatch', 'Acompanhe sua saúde', 990.00, TRUE),
('Videogame', 'O melhor desempenho para a sua melhor performance', 2399.90, TRUE),
('Headset', 'Escute cada detalhe do seu oponente', 499.90, TRUE),
('Headphone studio', 'Escute suas músicas preferidas como se você estivesse no estúdio de gravação', 799.99, TRUE),
('Earbud bluetooth', 'Menos um fio pra enrolar e os pets destruírem', 390.00, TRUE),
('Microondas', 'A praticidade concretizada', 399.90, TRUE),
('Ar-Condicionado', 'Deixe a temperatura do seu jeito', 1189.00, TRUE),
('Liquidificador', 'Perfeito para sucos e vitaminas', 179.90, TRUE),
('Air Fryer', 'Frita com ar quente', 390.00, TRUE),
('Aspirador de Pó', 'Limpeza sem esforço', 239.00, TRUE),
('Impressora', 'Seus documentos sempre em mãos', 899.90, TRUE),
('HD Externo', 'Armazene todos os seus arquivos', 179.90, TRUE),
('Roteador', 'Internet de alta velocidade', 299.90, TRUE),
('Cadeira de Escritório', 'Ergonômica e estilosa', 599.90, TRUE),
('Cadeira Gamer', 'Conforto para maratonas de jogos', 1299.99, TRUE),
('Bicicleta Elétrica', 'Mobilidade urbana ecológica', 2499.90, TRUE),
('Patinete Elétrico', 'Seu companheiro para trajetos urbanos', 1199.00, FALSE),
('Lavadoura lava e seca', 'Roupas limpas e secas com menos esforço', 1379.99, FALSE),
('E-Reader', 'Carregue uma biblioteca inteira com você', 639.90, TRUE),
('Câmera de Ação', 'Eternize suas aventuras', 1249.00, TRUE),
('Cafeteira', 'O café que você quiser em segundos', 229.00, FALSE),
('Impressora 3D', 'Dê vida às suas ideias', 1399.00, FALSE),
('Projetor Portátil', 'O cinema onde você quiser', 149.00, TRUE),
('Alimentador Automático para Pets', 'Comida fresquinha e água limpinha', 269.90, TRUE),
('Ventilador de teto', 'Só cai se o teto cair', 259.00, FALSE),
('Sofá Retrátil', 'Conforto e espaço para toda a família', 2599.90, FALSE),
('Mesa de Jantar', 'Perfeita para refeições em família', 899.90, TRUE),
('Cadeira de Madeira', 'Resistente e elegante', 199.90, TRUE),
('Cama Box Casal', 'Durma melhor todas as noites', 1899.90, TRUE),
('Suporte para TV', 'Organize sua sala com estilo', 599.90, TRUE),
('Estante para Livros', 'Espaço ideal para organizar sua biblioteca', 459.90, TRUE),
('Guarda-Roupa 3 Portas', 'Amplo e funcional para o seu quarto', 1199.90, TRUE),
('Mesa de Cabeceira', 'Pequeno e funcional para seu lado da cama', 199.90, TRUE),
('Mesa de Centro', 'Complemente sua sala com elegância', 299.90, TRUE),
('Poltrona Reclinável Ergonômica', 'Conforto e ergonomia', 649.90, FALSE),
('Banqueta Alta', 'Ideal para balcões e cozinhas modernas', 139.90, TRUE),
('Cama Infantil', 'Colorida e segura para os pequenos', 799.90, TRUE),
('Conjunto de Sofás', 'Estilo e conforto para sua sala', 3299.90, FALSE),
('Mesa de Escritório', 'Perfeita para home office', 499.90, TRUE),
('Prateleira Decorativa', 'Destaque seus objetos preferidos', 129.90, TRUE),
('Painel para TV', 'Praticidade e sofisticação para sua sala', 649.90, TRUE),
('Berço com Gavetas', 'Conforto e organização para o quarto do bebê', 1099.90, TRUE),
('Aparador', 'Ideal para corredores ou salas de jantar', 399.90, FALSE),
('Sapateira Vertical', 'Organize seus sapatos com estilo', 249.90, TRUE),
('Balcão de Cozinha', 'Funcionalidade e espaço extra', 759.90, TRUE),
('Armário de Cozinha', 'Organização e elegância na sua cozinha', 1199.90, TRUE),
('Colchão de Espuma', 'Noites tranquilas e confortáveis', 699.90, TRUE),
('Conjunto de Cadeiras', 'Conforto e design para sua mesa de jantar', 899.90, TRUE),
('Cama Queen Size', 'Espaço e conforto para seu descanso', 2499.90, TRUE),
('Mesa Lateral', 'Compacta e prática para qualquer ambiente', 179.90, TRUE),
('Cômoda 5 Gavetas', 'Armazenamento eficiente para roupas e acessórios', 799.90, TRUE),
('Beliche Infantil', 'Diversão e economia de espaço', 1499.90, TRUE),
('Buffet para Sala', 'Elegância e espaço para organizar sua louça', 999.90, TRUE),
('Penteadeira com Espelho', 'Seu cantinho de beleza perfeito', 1199.90, TRUE),
('Cama de Solteiro', 'Compacta e confortável para qualquer quarto', 549.90, TRUE);


